from selenium.webdriver.common.by import By


class YandexRoutsLocators:
    FROM = (By.ID, 'from')
    TO = (By.ID, 'to')
    MODE_OPTIMAL = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[1]/div[1]/div[1]')
    MODE_FAST = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[1]/div[1]/div[2]')
    MODE_MY = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[1]/div[1]/div[3]')
    CAR = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[1]/div[2]/div[1]')
    ON_FOOT = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[1]/div[2]/div[2]')
    TAXI = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[1]/div[2]/div[3]')
    BIKE = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[1]/div[2]/div[4]')
    SCOOTER = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[1]/div[2]/div[5]')
    CARSHARING = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[1]/div[2]/div[6]')
    BUTTON_ROUND = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[1]/div[3]/div[1]/button')
    TARIFF_EVERYDAY = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[1]/div[1]')
    TARIFF_MARCHING = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[1]/div[2]')
    TARIFF_LUX = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[1]/div[3]')
    BUTTON_DRIVER_LICENSE = (By.CLASS_NAME, 'np-button')
    FIRST_NAME = (By.ID, 'firstName')
    LAST_NAME = (By.ID, 'lastName')
    BIRTHDATE = (By.ID, 'birthDate')
    DRIVER_LICENSE_NUMBER = (By.ID, 'number')
    BUTTON_DRIVE_LICENSE_FORM_SUBMIT = (By.XPATH, '//*[@id="root"]/div/div[1]/div[2]/div[1]/form/div[2]/button[1]')
    BUTTON_AGREE = (By.XPATH, '//*[@id="root"]/div/div[1]/div[2]/div[2]/button[2]')
    BUTTON_PAYMENT = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[3]/div[2]')
    ADD_CARD = (By.CLASS_NAME, 'pp-plus')
    CARD_NUMBER = (By.XPATH, '/html/body/div/div/div[2]/div[2]/div[2]/form/div[1]/div[1]/div[2]/input')
    CODE_NUMBER = (By.ID, 'code')
    BUTTON_CARD_SUBMIT = (By.XPATH, '//*[@id="root"]/div/div[2]/div[2]/div[2]/form/div[3]/button[1]')
    BUTTON_CLOSE_PAYMENT = (By.XPATH, '//*[@id="root"]/div/div[2]/div[2]/div[1]/button')
    BUTTON_SMART = (By.CLASS_NAME, 'smart-button')
    RESULT = (By.CLASS_NAME, 'order-header')
